apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "mongo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "mongo.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
      {{- include "mongo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongo
        envFrom:
          - secretRef:
              name: {{ include "mongo.name" . }}
        ports:
          - name: mongo
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        volumeMounts:
        {{ if .Values.persistence.enabled }}
          - name: data
            mountPath: /data/db
        {{ end }}
      volumes:
      {{ if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mongo.name" . }}
      {{ end }}
