apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  MONGO_INITDB_ROOT_USERNAME: {{ printf .Values.secret.mongo.MONGO_INITDB_ROOT_USERNAME | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ printf .Values.secret.mongo.MONGO_INITDB_ROOT_PASSWORD | b64enc }}
